package com.invoiceguard.alert.entity;

public enum AlertType {
    CRITICAL_RISK_INVOICE,
    DUPLICATE_INVOICE,
    VENDOR_BANK_CHANGED,
    VENDOR_SUSPENDED,
    REPEATED_LOGIN_FAILURE,
    APPROVAL_OVERDUE,
    API_RATE_LIMIT_EXCEEDED,
    UNUSUAL_VENDOR_ACTIVITY,
    PAYMENT_BLOCKED
}
