package com.invoiceguard.risk.entity;

/** The full set of deterministic risk rules the engine evaluates. See individual rule classes in risk.rule. */
public enum RiskRuleCode {
    EXACT_DUPLICATE,
    NEAR_DUPLICATE,
    BANK_DETAILS_CHANGED,
    UNKNOWN_VENDOR,
    UNVERIFIED_VENDOR,
    UNUSUAL_AMOUNT,
    TAX_MISMATCH,
    MISSING_PURCHASE_ORDER,
    DUPLICATE_PURCHASE_ORDER,
    FUTURE_INVOICE_DATE,
    OLD_INVOICE_DATE,
    ROUND_AMOUNT_PATTERN,
    WEEKEND_SUBMISSION,
    AFTER_HOURS_SUBMISSION,
    SUSPICIOUS_VENDOR_EMAIL,
    PAYMENT_REFERENCE_REUSED,
    RAPID_REPEAT_SUBMISSION,
    MULTIPLE_BANK_CHANGES,
    VENDOR_RECENTLY_CREATED,
    HIGH_RISK_COUNTRY,
    DESCRIPTION_MISMATCH
}
